name: IS_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  # --- Core Drivers (Conda is faster for these) ---
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - h5py
  - jupyter
  - jupyterlab
  - ipykernel
  - pip
  
  # --- Deep Learning ---
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8

  - pip:
    # --- EEG & Neuroimaging ---

    - mne==1.6.1
    - pyriemann
    - nilearn
    - nibabel
    - torchinfo
    - tqdm
    - optuna